/* Manifest version: a11w7hyv */
// Production service worker — offline-first caching for Blazor WASM PWA.
// service-worker-assets.js is auto-generated by the build and injected as self.assetsManifest.
importScripts('./service-worker-assets.js');

const cachePrefix = 'dailygroove-';
const cacheName   = `${cachePrefix}${self.assetsManifest.version}`;

const cacheIncludes = [/\.dll$/, /\.wasm/, /\.html/, /\.js$/, /\.json$/, /\.css$/, /\.png$/, /\.jpe?g$/, /\.gif$/, /\.ico$/, /\.woff2?$/, /\.blat$/, /\.dat$/];
const cacheExcludes = [/^service-worker\.js$/, /^service-worker-assets\.js$/];

self.addEventListener('install',  e => e.waitUntil(onInstall(e)));
self.addEventListener('activate', e => e.waitUntil(onActivate(e)));
self.addEventListener('fetch',    e => {
    if (e.request.method !== 'GET') return;
    e.respondWith(onFetch(e));
});

async function onInstall() {
    self.skipWaiting();
    const requests = self.assetsManifest.assets
        .filter(a => cacheIncludes.some(r => r.test(a.url)))
        .filter(a => !cacheExcludes.some(r => r.test(a.url)))
        .map(a => new Request(a.url, { integrity: a.hash, cache: 'no-cache' }));
    const cache = await caches.open(cacheName);
    await cache.addAll(requests);
}

async function onActivate() {
    const keys = await caches.keys();
    await Promise.all(
        keys.filter(k => k.startsWith(cachePrefix) && k !== cacheName)
            .map(k => caches.delete(k))
    );
    await clients.claim();
}

async function onFetch(event) {
    const cache = await caches.open(cacheName);

    // Navigation requests → serve index.html from cache
    if (event.request.mode === 'navigate') {
        return (await cache.match('index.html')) ?? fetch(event.request);
    }

    // All other GET requests → cache-first
    return (await cache.match(event.request)) ?? fetch(event.request);
}
